// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizWiz3.DataLayer;

#nullable disable

namespace QuizWiz3.Migrations
{
    [DbContext(typeof(DBQuizContext))]
    [Migration("20240408122409_second-update")]
    partial class secondupdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QuizWiz3.Models.Quiz", b =>
                {
                    b.Property<int>("quiz_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("quiz_Id"), 1L, 1);

                    b.Property<string>("correct_Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("option1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("option2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("option3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("option4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("quiz_Id");

                    b.ToTable("Quizs");
                });

            modelBuilder.Entity("QuizWiz3.Models.Submit", b =>
                {
                    b.Property<int>("submit_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("submit_Id"), 1L, 1);

                    b.Property<int>("quiz_Id")
                        .HasColumnType("int");

                    b.Property<string>("user_Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("submit_Id");

                    b.HasIndex("quiz_Id");

                    b.ToTable("Submits");
                });

            modelBuilder.Entity("QuizWiz3.Models.Submit", b =>
                {
                    b.HasOne("QuizWiz3.Models.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("quiz_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });
#pragma warning restore 612, 618
        }
    }
}
